# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Lineas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipomovimiento', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja'), ('TRANSLADO', 'Translado')], max_length=20, verbose_name='Tipo Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=0, default=0.0, max_digits=2, verbose_name='Stock')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('campaña', models.CharField(max_length=255, verbose_name='Campaña')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Deposito', verbose_name='Depósito')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('imagen', models.ImageField(upload_to='imagen')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Linea', verbose_name='Linea')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoDeposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=10, null=True, verbose_name='Stock')),
                ('unidadmedida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('LITRO', 'Litro')], default='UNIDAD', max_length=30, verbose_name='Unidad Medida')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Deposito', verbose_name='Depósito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Producto', verbose_name='Producto'),
        ),
    ]
